version: '3'

services:
  backend:
    container_name: app_backend
    build: ./Backend
    ports:
      - 3001:3001
    platform: linux/x86_64
    working_dir: /app-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PORT=3001
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=password
      - DB_HOST=db
      - DB_DATA=Cashforce_Database
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
  db:
    container_name: Cashforce_Database
    image: mysql:8.0.23
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s